### ISSUE TITLE
Templates from the ansible-galaxy repo and github repo are different. 

### ISSUE THREAD

**Issue by d3nisko** [Dell-Networking/ansible-role-dellos-vlan#23]
Hello,
I observed that when using python 3.7 ansible is failing to run the role with the following messge: 
 "msg": "'dict object' has no attribute 'iteritems'"

This is related to the fact that jinja2 templates uses deprecated method  iteritems()

{% for key,value in dellos_vlan.iteritems() %}

I was able to fix this by replacing iteritems with items. I can see this is fixed here in the github repo.
After installing the role one more time from ansible-galaxy I still can see iteritems is in the template.
Files where iteritems is used are: **Dell-Networking.dellos-vlan/templates/dellos***
Could you update content of the ansible-galaxy repo with the latest version of templates please? 
Thank you.

**Comment by skg-net** [comment]
Updated the Galaxy with latest release.
