### ISSUE TITLE
VLAN description error

### ISSUE THREAD

**Issue by usunnapu** [Dell-Networking/ansible-role-dellos-vlan#25]
https://github.com/Dell-Networking/ansible-role-dellos-vlan/blob/090a7556399058acfabc7ad54f36cea252c1cb57/templates/dellos10_vlan.j2#L40

when trying to give the description of a vlan, if the value is something with spaces for example "ansible playbook vlan", playbook execution hits an error as it is trying to run something like _description ansible playbook vlan_

There is a need to change the [line](https://github.com/Dell-Networking/ansible-role-dellos-vlan/blob/090a7556399058acfabc7ad54f36cea252c1cb57/templates/dellos10_vlan.j2#L40) to _description "{{ vlan_vars.description }}"_

**Comment by skg-net** [comment]
Commit https://github.com/Dell-Networking/ansible-role-dellos-vlan/commit/f116f969033d8af8ac8f6e376892f79769b53977 addressed this issue.
