### ISSUE TITLE
get structured information?

### ISSUE THREAD

**Issue by tiagoasousa** [Dell-Networking/ansible-role-dellos-vlan#7]
is it possible to levarage these roles to create/populate vlan inventory?
i would like to get structured data of the following:

vlanid
description
private vlan, primary|secondary(isolated/community)
interfaces tagged

is it possible with this module?
thanks

**Comment by skg-net** [comment]
@networkpadawan you can use the roles data model to configure. To get data in the structured format, please use the facts module or the below filters to parse into structured data 
http://docs.ansible.com/ansible/devel/user_guide/playbooks_filters.html#network-cli-filters
